"""
Module Description: Streamlit System Logs Page
Purpose: Renders live system log viewer with log level filtering, search, and download capabilities.
Author: Technical Lead
Version: 2.0.0
Dependencies: streamlit, pathlib, config.settings
"""

import sys
from pathlib import Path
_PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

import re
import streamlit as st
from config import settings
from app.components.header import render_header
from app.components.footer import render_footer


LOG_FILES = {
    "🖥️ App Log":            "app.log",
    "⚡ Performance Log":    "performance.log",
    "🔍 Recommendation Log": "recommendation.log",
    "🚨 Exception Log":      "exception.log",
}

LEVEL_COLORS = {
    "ERROR":   ("#f87171", "rgba(239,68,68,0.12)"),
    "WARNING": ("#fbbf24", "rgba(245,158,11,0.10)"),
    "INFO":    ("#34d399", "rgba(16,185,129,0.08)"),
    "DEBUG":   ("#818cf8", "rgba(99,102,241,0.08)"),
}

LEVEL_PATTERN = re.compile(r"\b(ERROR|WARNING|INFO|DEBUG)\b")


def parse_level(line: str) -> str:
    m = LEVEL_PATTERN.search(line)
    return m.group(1) if m else "INFO"


def render_log_line(line: str, index: int) -> None:
    """Renders a single coloured log line."""
    level = parse_level(line)
    text_col, bg_col = LEVEL_COLORS.get(level, ("#cbd5e1", "rgba(255,255,255,0.03)"))
    badge_html = (
        f'<span style="background:{bg_col};color:{text_col};font-size:0.65rem;'
        f'font-weight:700;padding:1px 7px;border-radius:8px;margin-right:0.5rem;'
        f'border:1px solid {text_col}33;letter-spacing:0.04em;">{level}</span>'
    )
    safe_line = line.replace("<", "&lt;").replace(">", "&gt;")
    st.markdown(
        f'<div style="font-family:\'Cascadia Code\',\'Fira Code\',monospace;'
        f'font-size:0.73rem;color:#cbd5e1;background:{bg_col};'
        f'border-left:3px solid {text_col};padding:0.35rem 0.8rem;'
        f'margin-bottom:2px;border-radius:0 6px 6px 0;word-break:break-all;">'
        f'{badge_html}{safe_line}</div>',
        unsafe_allow_html=True
    )


def main() -> None:
    """Renders the system logs viewer page."""
    from app.utils.session_manager import SessionManager
    from app.utils.theme import inject_custom_css
    SessionManager.initialize_session_state()
    inject_custom_css()

    render_header("📋 System Logs")

    st.markdown(
        '<p style="color:#94a3b8;font-size:0.92rem;margin-bottom:1.5rem;">'
        'Browse, filter, and search real-time logs generated by the training, recommendation, and system components.</p>',
        unsafe_allow_html=True
    )

    logs_dir = settings.BASE_DIR / "logs"

    # ── Controls Row ───────────────────────────────────────────────
    c1, c2, c3, c4 = st.columns([2, 1.5, 1.5, 1])

    with c1:
        selected_label = st.selectbox(
            "Log File",
            options=list(LOG_FILES.keys()),
            label_visibility="collapsed",
            key="log_file_select"
        )
    with c2:
        level_filter = st.multiselect(
            "Level Filter",
            options=["INFO", "WARNING", "ERROR", "DEBUG"],
            default=["INFO", "WARNING", "ERROR"],
            label_visibility="collapsed",
            key="log_level_filter"
        )
    with c3:
        search_query = st.text_input(
            "Search",
            placeholder="🔍 Search logs...",
            label_visibility="collapsed",
            key="log_search"
        )
    with c4:
        max_lines = st.selectbox(
            "Lines",
            options=[100, 250, 500, 1000],
            index=1,
            label_visibility="collapsed",
            key="log_max_lines"
        )

    st.markdown("---")

    # ── Load log file ──────────────────────────────────────────────
    log_filename = LOG_FILES[selected_label]
    log_path = logs_dir / log_filename

    if not log_path.exists() or log_path.stat().st_size == 0:
        st.markdown(
            f'<div class="glass-card" style="text-align:center;padding:2rem;">'
            f'<div style="font-size:2rem;margin-bottom:0.6rem;">📭</div>'
            f'<div style="color:#94a3b8;font-size:0.88rem;">'
            f'Log file <code style="color:#a78bfa;">{log_filename}</code> is empty or does not exist yet.</div>'
            f'</div>',
            unsafe_allow_html=True
        )
        render_footer()
        return

    # Read and filter lines
    try:
        with open(log_path, "r", encoding="utf-8", errors="replace") as f:
            all_lines = [l.rstrip() for l in f.readlines() if l.strip()]
    except Exception as e:
        st.error(f"Failed to read log file: {e}")
        render_footer()
        return

    # Apply level filter
    if level_filter:
        filtered_lines = [l for l in all_lines if parse_level(l) in level_filter]
    else:
        filtered_lines = all_lines

    # Apply search filter
    if search_query.strip():
        q = search_query.strip().lower()
        filtered_lines = [l for l in filtered_lines if q in l.lower()]

    # Tail latest lines
    display_lines = filtered_lines[-max_lines:]

    # ── Stats row ─────────────────────────────────────────────────
    total = len(all_lines)
    errors = sum(1 for l in all_lines if "ERROR" in l)
    warnings = sum(1 for l in all_lines if "WARNING" in l)
    shown = len(display_lines)

    s1, s2, s3, s4 = st.columns(4)
    stat_items = [
        (s1, str(total),    "Total Lines",      "#a78bfa"),
        (s2, str(errors),   "Errors",           "#f87171"),
        (s3, str(warnings), "Warnings",         "#fbbf24"),
        (s4, str(shown),    f"Showing (last {max_lines})", "#34d399"),
    ]
    for col, val, lbl, color in stat_items:
        with col:
            st.markdown(
                f'<div style="background:rgba(255,255,255,0.04);border:1px solid rgba(255,255,255,0.08);'
                f'border-radius:12px;padding:0.8rem 1rem;text-align:center;">'
                f'<div style="font-size:1.5rem;font-weight:800;color:{color};">{val}</div>'
                f'<div style="font-size:0.72rem;color:#94a3b8;text-transform:uppercase;letter-spacing:0.06em;margin-top:0.2rem;">{lbl}</div>'
                f'</div>',
                unsafe_allow_html=True
            )

    st.markdown("<br>", unsafe_allow_html=True)

    # ── Download button ────────────────────────────────────────────
    col_dl, col_info = st.columns([1, 4])
    with col_dl:
        st.download_button(
            label="⬇️ Download Log",
            data="\n".join(all_lines),
            file_name=log_filename,
            mime="text/plain",
            use_container_width=True
        )
    with col_info:
        if not display_lines:
            st.info("No log entries match the current filter and search criteria.")

    st.markdown("---")

    # ── Log Viewer ────────────────────────────────────────────────
    if display_lines:
        st.markdown(
            f'<div style="font-size:0.75rem;color:rgba(148,163,184,0.5);margin-bottom:0.5rem;">'
            f'Displaying most recent <b style="color:#a78bfa;">{len(display_lines)}</b> entries'
            f'{" matching "" + search_query + """ if search_query else ""}.</div>',
            unsafe_allow_html=True
        )
        for i, line in enumerate(display_lines):
            render_log_line(line, i)

    render_footer()


if __name__ == "__main__":
    main()
